# Generated by Django 4.0.4 on 2022-06-11 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.CharField(default=uuid.UUID('b00957ab-3edf-440c-98b9-f576e3d117b2'), max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('cumpleaños', models.DateField()),
            ],
        ),
    ]
